### ISSUE TITLE
Error prompt

### ISSUE THREAD

**Issue by wmchina** [python-websockets/websockets#1066]
Hello, I have the following problems when using it. The code I tested is as follows:

```python
#!/usr/bin/env python

# WS server example
#https://websockets.readthedocs.io/en/stable/intro/index.html
import asyncio
import websockets

async def hello(websocket, path):
    name = await websocket.recv()
    print(f"<<< {name}")

    greeting = f"Hello {name}!"

    await websocket.send(greeting)
    print(f">>> {greeting}")

async def main():
    async with websockets.serve(hello, "0.0.0.0", 8866):
        await asyncio.Future()  # run forever

asyncio.run(main())
```

Error 

```
C:\Users\Administrator\Desktop\main>python main.py
connection handler failed
Traceback (most recent call last):
  File "C:\Program Files\python\lib\asyncio\windows_events.py", line 480, in finish_recv
    return ov.getresult()
OSError: [WinError 64] 指定的网络名不再可用。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\websockets\legacy\protocol.py", line 944, in transfer_data
    message = await self.read_message()
  File "C:\Program Files\python\lib\site-packages\websockets\legacy\protocol.py", line 1013, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "C:\Program Files\python\lib\site-packages\websockets\legacy\protocol.py", line 1089, in read_data_frame
    frame = await self.read_frame(max_size)
  File "C:\Program Files\python\lib\site-packages\websockets\legacy\protocol.py", line 1144, in read_frame
    frame = await Frame.read(
  File "C:\Program Files\python\lib\site-packages\websockets\legacy\framing.py", line 70, in read
    data = await reader(2)
  File "C:\Program Files\python\lib\asyncio\streams.py", line 708, in readexactly
    await self._wait_for_data('readexactly')
  File "C:\Program Files\python\lib\asyncio\streams.py", line 502, in _wait_for_data
    await self._waiter
  File "C:\Program Files\python\lib\asyncio\proactor_events.py", line 282, in _loop_reading
    length = fut.result()
  File "C:\Program Files\python\lib\asyncio\windows_events.py", line 812, in _poll
    value = callback(transferred, key, ov)
  File "C:\Program Files\python\lib\asyncio\windows_events.py", line 484, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] 指定的网络名不再可用。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\websockets\legacy\server.py", line 224, in handler
    await self.ws_handler(self, path)
  File "C:\Users\Administrator\Desktop\main\main.py", line 9, in hello
    name = await websocket.recv()
  File "C:\Program Files\python\lib\site-packages\websockets\legacy\protocol.py", line 552, in recv
    await self.ensure_open()
  File "C:\Program Files\python\lib\site-packages\websockets\legacy\protocol.py", line 920, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
```
How to solve this problem

**Comment by wmchina** [comment]
![4](https://user-images.githubusercontent.com/46123608/136544656-ce210ca5-e3fd-4275-8fc2-ad0942afdd2c.png)
