### ISSUE TITLE
A Suggestion about exception at legacy/server debbuging

### ISSUE THREAD

**Issue by hokaso** [python-websockets/websockets#1309]
code/func at: [     def write_http_response(](https://github.com/aaugustin/websockets/blob/ba1ed7a65cc876ff4e0fcd4dd4711402836475e2/src/websockets/legacy/server.py#L294)

The reason why there is this suggestion is because I found in the debug that a problem that a bug cannot pop up in an exception, I mistakenly gave 'status: http.HTTPStatus' int type, and directly the 'connection closed' accrued... Since there is no exception, I can only manually break the point until the program is interrupted. So if possible, can you add try except and throw some exceptions here? In this way, if there are similar problems with developers in the future, they can find the root cause of the problem quickly.

**Comment by aaugustin** [comment]
Indeed, modifying `example/faq/health_check_server.py` as follows:

```diff
diff --git a/example/faq/health_check_server.py b/example/faq/health_check_server.py
index 7b8bded..48ae99d 100755
--- a/example/faq/health_check_server.py
+++ b/example/faq/health_check_server.py
@@ -1,12 +1,14 @@
 #!/usr/bin/env python

 import asyncio
-import http
+import logging
 import websockets

+logging.basicConfig(level=logging.DEBUG)
+
 async def health_check(path, request_headers):
     if path == "/healthz":
-        return http.HTTPStatus.OK, [], b"OK\n"
+        return 200, [], b"OK\n"

 async def echo(websocket):
     async for message in websocket:
```

Results in:

```
$ curl http://127.0.0.1:8765/healthz
curl: (52) Empty reply from server
```

And logs say:

```
DEBUG:websockets.server:= connection is CONNECTING
DEBUG:websockets.server:< GET /healthz HTTP/1.1
DEBUG:websockets.server:< Host: 127.0.0.1:8765
DEBUG:websockets.server:< User-Agent: curl/7.85.0
DEBUG:websockets.server:< Accept: */*
INFO:websockets.server:connection closed
DEBUG:websockets.server:= connection is CLOSED
```

**Comment by aaugustin** [comment]
Options for fixing include:

1. Adding exception handling — but we're already two levels deep in exception handling

```diff
diff --git a/src/websockets/legacy/server.py b/src/websockets/legacy/server.py
index 399df85..46677e1 100644
--- a/src/websockets/legacy/server.py
+++ b/src/websockets/legacy/server.py
@@ -224,12 +224,19 @@ class WebSocketServerProtocol(WebSocketCommonProtocol):
                 headers.setdefault("Content-Type", "text/plain")
                 headers.setdefault("Connection", "close")

-                self.write_http_response(status, headers, body)
-                self.logger.info(
-                    "connection failed (%d %s)", status.value, status.phrase
-                )
-                await self.close_transport()
-                return
+                try:
+                    self.write_http_response(status, headers, body)
+                except Exception:
+                    self.logger.error(
+                        "failed to write handshake response", exc_info=True,
+                    )
+                else:
+                    self.logger.info(
+                        "connection failed (%d %s)", status.value, status.phrase
+                    )
+                finally:
+                    await self.close_transport()
+                    return

             try:
                 await self.ws_handler(self)
```

```
DEBUG:asyncio:Using selector: KqueueSelector
INFO:websockets.server:server listening on 127.0.0.1:8765
INFO:websockets.server:server listening on [::1]:8765
DEBUG:websockets.server:= connection is CONNECTING
DEBUG:websockets.server:< GET /healthz HTTP/1.1
DEBUG:websockets.server:< Host: 127.0.0.1:8765
DEBUG:websockets.server:< User-Agent: curl/7.85.0
DEBUG:websockets.server:< Accept: */*
ERROR:websockets.server:failed to write handshake response
Traceback (most recent call last):
  File "/Users/myk/dev/websockets/src/websockets/legacy/server.py", line 164, in handler
    await self.handshake(
  File "/Users/myk/dev/websockets/src/websockets/legacy/server.py", line 613, in handshake
    raise AbortHandshake(*early_response)
websockets.exceptions.AbortHandshake: HTTP 200, 5 headers, 3 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myk/dev/websockets/src/websockets/legacy/server.py", line 228, in handler
    self.write_http_response(status, headers, body)
  File "/Users/myk/dev/websockets/src/websockets/legacy/server.py", line 313, in write_http_response
    self.logger.debug("> HTTP/1.1 %d %s", status.value, status.phrase)
                                          ^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'value'
DEBUG:websockets.server:x closing TCP connection
DEBUG:websockets.server:= connection is CLOSED
INFO:websockets.server:connection closed
```


2. Adding a check for this type — but this feels oddly specific; if you want this, you should use a type checker

```diff
diff --git a/src/websockets/legacy/server.py b/src/websockets/legacy/server.py
index 399df85..8a802cf 100644
--- a/src/websockets/legacy/server.py
+++ b/src/websockets/legacy/server.py
@@ -603,6 +603,8 @@ class WebSocketServerProtocol(WebSocketCommonProtocol):
             )

         if early_response is not None:
+            if isinstance(early_response[0], int):
+                raise TypeError("...")
             raise AbortHandshake(*early_response)

         key = check_request(request_headers)
```

```
DEBUG:asyncio:Using selector: KqueueSelector
INFO:websockets.server:server listening on [::1]:8765
INFO:websockets.server:server listening on 127.0.0.1:8765
DEBUG:websockets.server:= connection is CONNECTING
DEBUG:websockets.server:< GET /healthz HTTP/1.1
DEBUG:websockets.server:< Host: 127.0.0.1:8765
DEBUG:websockets.server:< User-Agent: curl/7.85.0
DEBUG:websockets.server:< Accept: */*
ERROR:websockets.server:opening handshake failed
Traceback (most recent call last):
  File "/Users/myk/dev/websockets/src/websockets/legacy/server.py", line 164, in handler
    await self.handshake(
  File "/Users/myk/dev/websockets/src/websockets/legacy/server.py", line 607, in handshake
    raise TypeError("...")
TypeError: blablabla
DEBUG:websockets.server:> HTTP/1.1 500 Internal Server Error
DEBUG:websockets.server:> Date: Wed, 29 Mar 2023 05:37:28 GMT
DEBUG:websockets.server:> Server: Python/3.11 websockets/11.0.dev54+g399db68.dirty
DEBUG:websockets.server:> Content-Length: 76
DEBUG:websockets.server:> Content-Type: text/plain
DEBUG:websockets.server:> Connection: close
DEBUG:websockets.server:> [body] (76 bytes)
INFO:websockets.server:connection failed (500 Internal Server Error)
DEBUG:websockets.server:x closing TCP connection
DEBUG:websockets.server:= connection is CLOSED
INFO:websockets.server:connection closed
```

Probably I prefer the first solution. If we do this, it will require writing a test.

**Comment by aaugustin** [comment]
I decided to convert int to HTTPStatus, which fixes this particular issue and likely improves the UX.
