### ISSUE TITLE
Is this reconverable (502 after ConnectionClose)?

### ISSUE THREAD

**Issue by FrankC01** [python-websockets/websockets#1384]
Wondering if there is more I can do in the following scenario (log follows code below)?

Here is the connect logic:
```python
            async for websock in ws_connect(
                self.config.socket_url,
                extra_headers=self._ADDITIONL_HEADER,
                ssl=ssl.SSLContext(ssl.PROTOCOL_SSLv23),
            ):
                try:
                    res = await self._subscription_drive(
                        self._PAYLOAD_TEMPLATE.copy(),
                        builder,
                        websock,
                        handler,
                    )
                    logger.info(
                        f"Subscription listener returning in shutdown: {self._in_shutdown}"
                    )
                    await websock.close()
                    return res
                except (ConnectionClosed, ConnectionClosedError) as ws_cc:
                    ws_e_name = type(ws_cc).__name__
                    if continue_on_close and not self._in_shutdown:
                        logger.warning(
                            f"Subscription listener {ws_e_name}... reconnecting"
                        )
                        continue
                    else:
                        logger.error(
                            f"Subscription listener {ws_e_name} occured for shutdown -> {self._in_shutdown} {ws_cc.args}"
                        )
                        return SuiRpcResult(False, "ConnectionClosed", ws_cc)
                except Exception as exc:
                    e_name = type(exc).__name__
                    logger.error(
                        f"Subscription listener {e_name} occured in shutdown -> {self._in_shutdown} {exc.args}"
                    )
                    return SuiRpcResult(False, e_name, exc)
```

I have enabled the log and this is what I'm getting:
```bash
2023-07-19 17:05:56,880 - pysui.subscribe - WARNING - Subscription listener ConnectionClosedError... reconnecting
2023-07-19 17:05:56,930 - websockets.client - INFO - ! connect failed; reconnecting in 0.9 seconds
Traceback (most recent call last):
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 602, in __aiter__
    async with self as protocol:
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 637, in __aenter__
    return await self
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 662, in __await_impl__
    await protocol.handshake(
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 329, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 502
2023-07-19 17:05:58,869 - websockets.client - INFO - ! connect failed again; retrying in 3 seconds
Traceback (most recent call last):
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 602, in __aiter__
    async with self as protocol:
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 637, in __aenter__
    return await self
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 662, in __await_impl__
    await protocol.handshake(
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 329, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 502
2023-07-19 17:06:01,897 - websockets.client - INFO - ! connect failed again; retrying in 5 seconds
Traceback (most recent call last):
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 602, in __aiter__
    async with self as protocol:
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 637, in __aenter__
    return await self
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 662, in __await_impl__
    await protocol.handshake(
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 329, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 502
2023-07-19 17:06:06,928 - websockets.client - INFO - ! connect failed again; retrying in 8 seconds
Traceback (most recent call last):
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 602, in __aiter__
    async with self as protocol:
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 637, in __aenter__
    return await self
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 662, in __await_impl__
    await protocol.handshake(
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 329, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 502
2023-07-19 17:06:15,988 - websockets.client - INFO - ! connect failed again; retrying in 13 seconds
Traceback (most recent call last):
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 602, in __aiter__
    async with self as protocol:
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 637, in __aenter__
    return await self
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 662, in __await_impl__
    await protocol.handshake(
  File "/home/ec2-user/.pyenv/versions/trading_algo_3_10/lib/python3.10/site-packages/websockets/legacy/client.py", line 329, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 502
```

**Comment by aaugustin** [comment]
Nope. Server is down. All you can do is wait and retry later.
