### ISSUE TITLE
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x555e8f241810>; the handler is closed

### ISSUE THREAD

**Issue by djccnt15** [python-websockets/websockets#1394]
Hello~ I guess you've already fix this bug.. but the issue raised to me
the issue not always raises, but intermittently.
I guess the issue raise when the server is called after it is idle for some time, and it works fine after a bit of time after the issue raised
the server is tested in through Google Chrome 116

My dependencies are like below

- gunicorn==20.1.0
- uvicorn==0.21.1
- uvloop==0.17.0
- websockets==11.0.3

I run server with the command below

```
gunicorn main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker
```

and the traceback is like below

```
Traceback (most recent call last):
  File "/fastapi/settings/database.py", line 30, in get_db
    yield db
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/fastapi/src/endpoints/bill_img.py", line 46, in img_list
    total, img_list = await read_billimg_list(db, start, end, keyword)
  File "/fastapi/src/crud/bill_img.py", line 47, in read_billimg_list
    total = await db.execute(select(func.count()).select_from(q))
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 313, in execute
    result = await greenlet_spawn(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 165, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2124, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 253, in orm_execute_statement
    result = conn.execute(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2329, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/aiomysql.py", line 99, in execute
    return self.await_(self._execute_async(operation, parameters))
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/aiomysql.py", line 111, in _execute_async
    result = await self._cursor.execute(operation, parameters)
  File "/usr/local/lib/python3.10/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/usr/local/lib/python3.10/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/usr/local/lib/python3.10/site-packages/aiomysql/connection.py", line 468, in query
    await self._execute_command(COMMAND.COM_QUERY, sql)
  File "/usr/local/lib/python3.10/site-packages/aiomysql/connection.py", line 713, in _execute_command
    self._write_bytes(prelude + sql[:chunk_size - 1])
  File "/usr/local/lib/python3.10/site-packages/aiomysql/connection.py", line 658, in _write_bytes
    return self._writer.write(data)
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 325, in write
    self._transport.write(data)
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x555e8f241810>; the handler is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 15, in __call__
    async with AsyncExitStack() as stack:
  File "/usr/local/lib/python3.10/contextlib.py", line 714, in __aexit__
    raise exc_details[1]
  File "/usr/local/lib/python3.10/contextlib.py", line 697, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/usr/local/lib/python3.10/contextlib.py", line 217, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/fastapi/settings/database.py", line 32, in get_db
    await db.close()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 840, in close
    await greenlet_spawn(self.sync_session.close)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 165, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2380, in close
    self._close_impl(invalidate=False)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2422, in _close_impl
    transaction.close(invalidate)
  File "<string>", line 2, in close
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1327, in close
    transaction.close()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2559, in close
    self._do_close()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2697, in _do_close
    self._close_impl()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2683, in _close_impl
    self._connection_rollback_impl()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2675, in _connection_rollback_impl
    self.connection._rollback_impl()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1118, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2329, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1116, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 657, in do_rollback
    dbapi_connection.rollback()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/aiomysql.py", line 207, in rollback
    self.await_(self._connection.rollback())
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.10/site-packages/aiomysql/connection.py", line 398, in rollback
    await self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/usr/local/lib/python3.10/site-packages/aiomysql/connection.py", line 713, in _execute_command
    self._write_bytes(prelude + sql[:chunk_size - 1])
  File "/usr/local/lib/python3.10/site-packages/aiomysql/connection.py", line 658, in _write_bytes
    return self._writer.write(data)
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 325, in write
    self._transport.write(data)
  File "uvloop/handles/stream.pyx", line 674, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x555e8f241810>; the handler is closed
```

**Comment by aaugustin** [comment]
Hello, the traceback involves unicorn, starlette, fastapi, sqlalchemy, aiomysql, and uvloop, but not websockets -- so I don't think this is the right place to discuss it.

**Comment by djccnt15** [comment]
> Hello, the traceback involves unicorn, starlette, fastapi, sqlalchemy, aiomysql, and uvloop, but not websockets -- so I don't think this is the right place to discuss it.

oh.. Yes.. You're right.. Sry for bothering.. I hope I could delete this issue

**Comment by aaugustin** [comment]
I'm deleting it :-)
