### ISSUE TITLE
'WebSocketServerProtocol' object has no attribute 'protocol' when using broadcast

### ISSUE THREAD

**Issue by mvdwetering** [python-websockets/websockets#1524]
I am trying to use the `broadcast` function to broadcast to all connected clients. I think I am using the [example code](https://websockets.readthedocs.io/en/stable/faq/server.html#how-do-i-send-a-message-to-all-users) correctly, but I get the following error. 

```
Traceback (most recent call last):
  File "/home/michel/remote_systemmonitor/./broaccast_test.py", line 29, in <module>
    asyncio.run(main())
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/michel/remote_systemmonitor/./broaccast_test.py", line 25, in main
    message_all(f"test {count}")
  File "/home/michel/remote_systemmonitor/./broaccast_test.py", line 17, in message_all
    broadcast(CONNECTIONS, message)
  File "/home/michel/remote_systemmonitor/venv/lib/python3.12/site-packages/websockets/asyncio/connection.py", line 1114, in broadcast
    if connection.protocol.state is not OPEN:
       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'WebSocketServerProtocol' object has no attribute 'protocol'. Did you mean: 'subprotocol'?
```

I don't understand how the protocol can be missing because it seems like it should be automatically set?

I have been cutting down my code and I have the same with what is basically the example code as far as I can tell.

```
#!/usr/bin/env python

import asyncio
from websockets import serve
from websockets.asyncio.server import broadcast

CONNECTIONS = set()

async def handler(websocket):
    CONNECTIONS.add(websocket)
    try:
        await websocket.wait_closed()
    finally:
        CONNECTIONS.remove(websocket)

def message_all(message):
    broadcast(CONNECTIONS, message)

async def main():
    async with serve(handler, "localhost", 8765):
        count = 1
        while True:
            await asyncio.sleep(10)
            print(f"test {count}")
            message_all(f"test {count}")
            count = count + 1

if __name__ == "__main__":
    asyncio.run(main())    
```

Note that I am new to websockets so it is probably on my side, but I don't see how.

**Comment by aaugustin** [comment]
Use `from websockets.asyncio.server import serve`.

Your problem is that `from websockets import serve` gives you the legacy asyncio implementation of `serve`, while `from websockets.asyncio.server import broadcast` gives you the version of broadcast that's designed for the new asyncio implementation, and those are incompatible.

**Comment by mvdwetering** [comment]
Thanks, that indeed solves it.

Not sure how I got that import. The examples seem to all have the correct one (as expected). Maybe the IDE helped me 🫤
