### ISSUE TITLE
File "websockets\sync\connection.py", line 891, in close_socket AssertionError

### ISSUE THREAD

**Issue by albertyue** [python-websockets/websockets#1558]
my program terminated with uncaught exception, here is the traceback log:
```
2024-11-28 18:40:25,154: websockets.server->send_context [DEBUG] ! error while sending data
Traceback (most recent call last):
  File "websockets\sync\connection.py", line 789, in send_context
  File "websockets\sync\connection.py", line 855, in send_data
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2024-11-28 18:40:25,154: websockets.server->recv_events [DEBUG] ! error while receiving data
Traceback (most recent call last):
  File "websockets\sync\connection.py", line 640, in recv_events
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2024-11-28 18:40:25,155: websockets.server->parse [DEBUG] < EOF
2024-11-28 18:40:25,155: root->except_hook [ERROR] Uncaught exception
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
  File "websockets\sync\server.py", line 204, in recv_events
  File "websockets\sync\connection.py", line 728, in recv_events
  File "websockets\sync\connection.py", line 891, in close_socket
AssertionError
```
seems like the connection not closed normally, maybe caused by poor network connectivity. 
Is there any work-around ？
I would appreciate it if you could help me figure out what happend.

***
websockets version：14.0

**Comment by aaugustin** [comment]
Do you have an example that produces this problem? This would help me locate what causes this problem.

----

It looks like my reasoning here is incorrect:
```python
        # Calling protocol.receive_eof() is safe because it's idempotent.
        # This guarantees that the protocol state becomes CLOSED.
        self.protocol.receive_eof()
        assert self.protocol.state is CLOSED
```

After `protcol.receive_eof()`, regardless of whether `protocol.parser` is `protocol.parse()` or `protocol.discard()`, `next(protocol.parser)` is expected to complete and set `protocol.state` to `CLOSED`.
