### ISSUE TITLE
Error on switching to new asyncio

### ISSUE THREAD

**Issue by drc38** [python-websockets/websockets#1566]
Hi,

I need to do a bit more debugging but is this error expected when switching to the new asyncio from the legacy implementation? 

Thanks

```
Error doing job: Fatal error: protocol.data_received() call failed. (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 1019, in _read_ready__data_received
    self._protocol.data_received(data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/asyncio/connection.py", line 1082, in data_received
    self.process_event(event)
    ~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/asyncio/server.py", line 218, in process_event
    super().process_event(event)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/asyncio/connection.py", line 733, in process_event
    self.acknowledge_pings(bytes(event.data))
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/asyncio/connection.py", line 753, in acknowledge_pings
    pong_waiter.set_result(latency)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
asyncio.exceptions.InvalidStateError: invalid state
```

It appears to be due to trying to process incoming 0 byte ping/pongs:
```
2024-12-29 09:56:44.343 DEBUG (MainThread) [websockets.server] < PING '' [0 bytes]
2024-12-29 09:56:44.343 DEBUG (MainThread) [websockets.server] > PONG '' [0 bytes]
2024-12-29 09:56:46.094 DEBUG (MainThread) [websockets.server] > PING 20 71 45 d0 [binary, 4 bytes]
```

**Comment by drc38** [comment]
Extra debug:
```
2024-12-30 21:46:20.130 DEBUG (MainThread) [websockets.server] > PING 8c 77 10 4c [binary, 4 bytes]
2024-12-30 21:46:20.339 DEBUG (MainThread) [websockets.server] < PONG 8c 77 10 4c [binary, 4 bytes]
2024-12-30 21:46:40.341 DEBUG (MainThread) [websockets.server] > PING 0d 90 0f 00 [binary, 4 bytes]
2024-12-30 21:46:40.855 DEBUG (MainThread) [websockets.server] < PONG 0d 90 0f [binary, 3 bytes]
2024-12-30 21:47:17.717 DEBUG (MainThread) [websockets.server] < PING '' [0 bytes]
2024-12-30 21:47:17.717 DEBUG (MainThread) [websockets.server] > PONG '' [0 bytes]
2024-12-30 21:47:18.363 DEBUG (MainThread) [websockets.server] < TEXT '[2,"27db2f45-d1d7-91b4-2aee-4b60975d27ce","Mete...,"value":"50.100"}]}]}]' [735 bytes]
2024-12-30 21:47:18.392 DEBUG (MainThread) [websockets.server] > TEXT '[3,"27db2f45-d1d7-91b4-2aee-4b60975d27ce",{}]' [45 bytes]
2024-12-30 21:47:37.764 DEBUG (MainThread) [websockets.server] > PING c7 27 2c d6 [binary, 4 bytes]
2024-12-30 21:47:37.898 DEBUG (MainThread) [websockets.server] < PONG c7 27 2c d6 [binary, 4 bytes]
2024-12-30 21:47:37.898 DEBUG (MainThread) [websockets.server] pong_waiter.set_result failed on ping_id: b'\r\x90\x0f\x00'
2024-12-30 21:47:37.898 DEBUG (MainThread) [websockets.server] Ping_ids: [b'\r\x90\x0f\x00']
2024-12-30 21:47:37.898 DEBUG (MainThread) [websockets.server] Data: b"\xc7',\xd6"
```

By adding the following:
```
            try:
                pong_waiter.set_result(latency)
            except Exception:
                self.logger.debug("pong_waiter.set_result failed on ping_id: %s", ping_id)
                self.logger.debug("Ping_ids: %s", ping_ids)
                self.logger.debug("Data: %s", data)
```

**Comment by drc38** [comment]
Looks like this line where the trailing 00 is lost could be the cause:
`2024-12-30 21:46:40.855 DEBUG (MainThread) [websockets.server] < PONG 0d 90 0f [binary, 3 bytes]`

**Comment by drc38** [comment]
Another example where the data is not returned by the pong, I assume due to a network error:
```
2024-12-30 22:31:32.851 DEBUG (MainThread) [websockets.server] > PING d6 00 72 43 [binary, 4 bytes]
2024-12-30 22:31:33.017 DEBUG (MainThread) [websockets.server] < PONG d6 [binary, 1 byte]
2024-12-30 22:32:02.857 DEBUG (MainThread) [websockets.server] < PING '' [0 bytes]
2024-12-30 22:32:02.857 DEBUG (MainThread) [websockets.server] > PONG '' [0 bytes]
2024-12-30 22:32:12.858 DEBUG (MainThread) [websockets.server] > PING '_\x17W\x1b' [text, 4 bytes]
2024-12-30 22:32:13.034 DEBUG (MainThread) [websockets.server] < PONG '_\x17W\x1b' [text, 4 bytes]
2024-12-30 22:32:13.034 DEBUG (MainThread) [websockets.server] pong_waiter.set_result failed on ping_id: b'\xd6\x00rC'
2024-12-30 22:32:13.034 DEBUG (MainThread) [websockets.server] Ping_ids: [b'\xd6\x00rC']
2024-12-30 22:32:13.035 DEBUG (MainThread) [websockets.server] Data: b'_\x17W\x1b'
```

**Comment by aaugustin** [comment]
From the perspective of websockets there are two options:

1. make no changes; expect other implementations to improve
2. switch from "random payloads" to "random printable ASCII payloads"; improve compatibility

The problem isn't super frequent, which is why I didn't really consider option 2 until now.

**Comment by drc38** [comment]
Thanks for the reply, interestingly the error doesn't occur with the legacy implementation with the same client, was number 2 the previous approach? 

Could the scenarios above occur due to a flaky network connection rather than poor client implementation?  

Is there a 3rd option to timeout the pong future gracefully if it isn't received/matched before the next pong receipt?

**Comment by drc38** [comment]
I assume the above could be achieved by moving:
```
latency = pong_timestamp - ping_timestamp
pong_waiter.set_result(latency)
```
Into the if statement:
```
if ping_id == data:
    latency = pong_timestamp - ping_timestamp
    pong_waiter.set_result(latency)
    self.latency = latency
    break
```

**Comment by aaugustin** [comment]
> Could the scenarios above occur due to a flaky network connection rather than poor client implementation?

No - websockets runs over TCP and TCP guarantees that there's no gap in the data stream.

**Comment by aaugustin** [comment]
I'm not 100% sure how you end up in this situation but I'm relatively confident that the change that I just made fixed it. Would you be able to test it?

You can just patch websockets like this:

https://github.com/python-websockets/websockets/commit/197b3ec2c7acf3a3804a94c0c02ed8e27051b0f0#diff-76885032aeb05335d0dc3238fcc783c2af021b1b13d46b3b0401d64956912aa8L753-R754

**Comment by drc38** [comment]
Thanks, will test but the patch looks good to me.

**Comment by aaugustin** [comment]
Cool, thank you for reporting the bug!

**Comment by drc38** [comment]
> Cool, thank you for reporting the bug!

Been running patch for 12h with no issues
