### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by ghost** [python-websockets/websockets#4]
The following command: 

```
pip install git+https://github.com/aaugustin/websockets.git
```

with the following logged by pip:

```
------------------------------------------------------------
/home/amirouche/.virtualenvs/suprm3/bin/pip run on Thu Oct 24 01:24:34 2013
Downloading/unpacking git+https://github.com/aaugustin/websockets.git

  Cloning https://github.com/aaugustin/websockets.git to /tmp/pip-tgmzlg-build

  Found command 'git' at '/usr/bin/git'
  Running command /usr/bin/git clone -q https://github.com/aaugustin/websockets.git /tmp/pip-tgmzlg-build
  Running setup.py egg_info for package from git+https://github.com/aaugustin/websockets.git

    Traceback (most recent call last):

      File "<string>", line 16, in <module>

      File "/tmp/pip-tgmzlg-build/setup.py", line 11, in <module>

        with open(os.path.join(root, 'README')) as f:

    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-tgmzlg-build/README'

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-tgmzlg-build/setup.py", line 11, in <module>

    with open(os.path.join(root, 'README')) as f:

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-tgmzlg-build/README'

----------------------------------------

Command python setup.py egg_info failed with error code 1 in /tmp/pip-tgmzlg-build

Exception information:
Traceback (most recent call last):
  File "/home/amirouche/.virtualenvs/suprm3/lib/python3.3/site-packages/pip-1.3.1-py3.3.egg/pip/basecommand.py", line 139, in main
    status = self.run(options, args)
  File "/home/amirouche/.virtualenvs/suprm3/lib/python3.3/site-packages/pip-1.3.1-py3.3.egg/pip/commands/install.py", line 266, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/amirouche/.virtualenvs/suprm3/lib/python3.3/site-packages/pip-1.3.1-py3.3.egg/pip/req.py", line 1057, in prepare_files
    req_to_install.run_egg_info()
  File "/home/amirouche/.virtualenvs/suprm3/lib/python3.3/site-packages/pip-1.3.1-py3.3.egg/pip/req.py", line 236, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/amirouche/.virtualenvs/suprm3/lib/python3.3/site-packages/pip-1.3.1-py3.3.egg/pip/util.py", line 662, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-tgmzlg-build
```

**Comment by 1captainnemo1** [comment]
websockets is a Python3-only module, Lower versions of python will not allows successful installation
